[package]
name = "musig-psbt"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = { optional = true }
bitcoin = { version = "0.29.2" }
bitcoin_hashes = { version = "~0.11" }
rand = { }
secp256k1-zkp = { git = "https://github.com/sanket1729/rust-secp256k1-zkp.git", rev = "32235b401a7df224aaf74de823e864384b731cea" }
clap = { version = "4.2.7", features = [ "derive" ], optional = true }

[features]
default = [ ]
test = [ "bitcoin/bitcoinconsensus" ]
with-musig-cli = [ "dep:base64", "dep:clap", "secp256k1-zkp/rand-std" ]

[[bin]]
name = "musig-cli"
required-features = [ "with-musig-cli" ]
